import { ProjectType } from "./projects";

export const myProjects: ProjectType[] = [
  {
    name: "Biamuta",
    id: "biamuta",
    desc: "Africa's first one stop shop for basic education. Enter a world of interactive learning with Biamuta! From English and Mathematics to Science and Social studies, fun games, exercises and much more, you are in for an exciting ride on Biamuta.",
    url: "https://biamuta.com/",
    img: "https://s3.amazonaws.com/alexius.dev/projectImgs/Biamuta.png",
    tech: ["React", "Redux", "Firebase", "Rive", "Styled-Components"],
  },
  {
    name: "Oda Now",
    id: "oda",
    desc: "An order management system, for tracking orders, keeping track of inventory, invoicing and customer managment.",
    url: "https://odanow.net/#/",
    img: "https://s3.amazonaws.com/alexius.dev/projectImgs/odanow.png",
    tech: ["React", "Asp.net", "Sql", "Redux"],
  },
  // {
  //   name: "Alexius",
  //   id: "portfolio",
  //   desc: "My personal website",
  //   url: "https://www.alexiusnwala.com/",
  //   img: "https://s3.amazonaws.com/alexius.dev/projectImgs/alexius.png",
  //   tech: [
  //     "Next.js",
  //     "Framer-motion",
  //     "Styled-Components",
  //     "Typescript",
  //   ],
  //   git: "https://github.com/Alexiuszz/portfolio",
  // },
  {
    name: "Granomaly",
    id: "grasp",
    desc: "Web Tool to manage system anomalies, in oil and gas industries",
    url: "http://grasp3-dev.eba-5ihibxwf.us-east-1.elasticbeanstalk.com/",
    img: "https://s3.amazonaws.com/alexius.dev/projectImgs/Granomaly.png",
    tech: [
      "React.js",
      "MaterialUI",
      "Asp.net",
      "Chart.js",
      "Redux",
      "MsSQL",
      "Aws Elastic Beanstalk",
    ],
    git: "https://github.com/Alexiuszz/Anomaly-Management",
  },
  {
    name: "Stay-focused",
    id: "focused",
    desc: "Productivity app, helps you track the time you've spent working.",
    url: "https://stay-focused-nine.vercel.app/",
    img: "https://s3.amazonaws.com/alexius.dev/projectImgs/Stay-focused.png",
    tech: [
      "Next.js",
      "ChartJS",
      "Tailwind Css",
      "Typescript",
    ],
    git: "https://github.com/Alexiuszz/stay-focused",
  },
  {
    name: "Emissar",
    id: "emissar",
    desc: "Courier hailing web app, for finding courier services around you!",
    url: "https://emissar.netlify.com/",
    img: "https://s3.amazonaws.com/alexius.dev/projectImgs/emissar.png",
    tech: [
      "React",
      "Redux",
      "Express.js",
      "MongoDb",
      "Google-Maps-API",
    ],
    git: "https://github.com/Alexiuszz/Courier_Finder",
  },
  {
    name: "BrainTrainer",
    id: "bt",
    desc: "Highly addictive web app for training your cognitive ability, with many game modes involving memory retention, arithmetic and logical reasoning.",
    url: "http://brain-trainer-web.s3-website-us-west-2.amazonaws.com/",
    img: "https://s3.amazonaws.com/alexius.dev/projectImgs/brain-trainer.png",
    tech: ["React", "Redux"],
  },
];
